version: '3'

services:
  preprocessor:
    image: data-preprocessor
    build:
      context: .
    container_name: data-preprocessor
    ports:
      - "8265:8265"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./input:/app/input
      - ./output:/app/output
      - ./processed:/app/processed
      - ./processed/broken:/app/processed/broken
    command: bash -c "python main.py --config config.yaml"
